- logsubprocess.py
- main.py
- processjunit.py
- run.py
- versions/3.0.0/ignore.yaml
- versions/3.2.0/ignore.yaml
- versions/3.4.0/ignore.yaml
- versions/3.5.0/ignore.yaml
Remove tests that require features unsupported by scylla -
secondary indexes and lightweight transactions.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
> Add an ignored list of tests for features unsupported by Scylla

- versions/datastax/3.23.0/ignore.yaml
- versions/datastax/3.23.0/patch
- versions/scylla/3.23.0/ignore.yaml
- versions/scylla/3.23.0/patch
Master and 3.23.0 does not work due to the using unsupported 'use_single_interface' option for ccm populate routine.
> fix(datastax patch): Make it work on the master

- run.py
Start checkout out not pure tag, but tag with "-scylla" at the end, for scylla repo only.
> fix(run.py): checkout scylla version

- run.py
Failed test: https://jenkins.scylladb.com/view/master/job/scylla-master/job/driver-tests/job/
python-driver-matrix-test/810/console
Error: TypeError: load() missing 1 required positional argument: 'Loader'
In pyyaml 6.0 the yaml.load() function requires parameter loader=Loader. Instead of that for simple
YAML (str, int, lists), can use yaml.safe_load()
> fix(ignore set): use safe_load instead of load

- versions/scylla/3.24.0/ignore.yaml
For Scylla's python-driver version 3.24.0 and protocol 4 this is flaky
(sometimes it fails)
```python
def test_connect_no_auth_provider(self):
cluster = TestCluster()
cluster.connect()
cluster.refresh_nodes()
down_hosts = [host for host in cluster.metadata.all_hosts() if not host.is_up]
>       self.assertEqual(len(down_hosts), 1)
E       AssertionError: 0 != 1
tests/integration/standard/test_authentication_misconfiguration.py:46: AssertionError
```
> fix(scylla/3.24.0/ignore.yaml): Marking test_connect_no_auth_provider as flaky

- processjunit.py
- tests/test_report.py
* Passed test will mark as `xpassed` if it marks as "ignore" or "flaky" 
test.
* test_is_report_failed - Adding a new test to verify "is_failed" property
returns True if the report contains errors or failures.
> fix(processjunit.py): Fixing "xpassed" logic for passed test

- main.py
* The repo's directory should be updated before extracting the
latest versions in case the directory exists.
* Rename variable from `is_python_driver` to `is_scylla_driver`
> fix(main.py): Updating repo before extract n the latest versions

- versions/datastax/3.24.0/patch.patch
- versions/datastax/3.25.0/patch.patch
- versions/scylla/3.24.0/patch.patch
- versions/scylla/3.25.0/patch.patch
`test_materialized_view_metadata_alter` is assuming default compaction
which is diffent in scylla-enterprise.
```
def test_materialized_view_metadata_alter(self):
"""
test for materialized view metadata alteration
test_materialized_view_metadata_alter tests that materialized view metadata is properly updated implicitly in the
table metadata once that view is updated. It creates a simple base table and then creates a view based
on that table. It then alters that materalized view and checks that the materialized view metadata is altered in
the table metadata.
@since 3.0.0
@jira_ticket PYTHON-371
@expected_result Materialized view metadata should be updated with the view is altered.
@test_category metadata
"""
>       self.assertIn("SizeTieredCompactionStrategy", …
```
> Fix latest patches to work on scylla enterprise version

- versions/scylla/3.25.2/ignore.yaml
- versions/scylla/3.25.2/patch.patch
New version fixed one of the test and removed the `@unittest.expectedFailure` decorator, hence the patch needed to be updated
> Fix the patches for scylla-driver==3.25.2

- versions/datastax/3.24.0/patch.patch
- versions/datastax/3.25.0/patch.patch
- versions/scylla/3.24.0/patch.patch
- versions/scylla/3.25.0/patch.patch
- versions/scylla/3.25.2/patch.patch
it wasn't waiting correctly for cluster to be up and
ready, and it was failing this test, and the next module
that was using the default test cluster
> fix test_connection_honor_cluster_port setup_module

- run.py
Since we have tests that now depend on `LibevConnection`
we need to make sure we compile the driver, and not just
relay on the default Connection which doens't need any
compilation.
Fixes: #44
> run.py: add build command so driver would be compiled

- run.py
otherwise next run would try to reuse existing clusters and they are already stopped and killed
> clean up ccm direcotry between run

- versions/datastax/3.26.0/ignore.yaml
- versions/datastax/3.26.0/patch.patch
Since unittest2 package was removed in 3.26.0, we
need to remove it's refernece from out patch to make it apply cleanly
Fix: #51
> Fix patch for datastax 3.26.0

- run.py
- versions/datastax/3.26.0/patch.patch
- versions/scylla/3.26.0/ignore.yaml
- versions/scylla/3.26.0/patch.patch
- Introduce a function to get scylla version correctly
- Introduce cluster cleanups for datastax versions
Fixes: #54
Fixes: #53
> Fix breakages of in python matrix

- README.md
- scripts/Dockerfile
- scripts/image
* cause of issue with scylla master, we should swith to jvm11
* update the base image to python 3.11
Fixes: #58
> Dockerfile: change from jvm8 to jvm11

- README.md
- scripts/Dockerfile
- scripts/image
- scripts/run_test.sh
- versions/scylla/3.26.2/ignore.yaml
- versions/scylla/3.26.2/patch.patch
since datastax versions don't yet completely support python3.11
also hardcode the `EVENT_LOOP_MANAGER` to `libev` and not
the `asyncio` that the pipeline passes down
> revert to python3.9

- versions/datastax/3.26.0/patch.patch
patch was using `experimental` which isn't support anymore, and node boot was failing like:
```
2023-09-20 05:28:40,323 DEBUG [__init__:430]: Removing cluster test_cluster
tests/integration/standard/test_policies.py::HostFilterPolicyTests::test_predicate_changes
ERROR 2023-09-20 05:28:40,230 [shard 0:main] init - Startup failed: std::runtime_error
(You must use both enable_user_defined_functions and experimental_features:udf to enable user-defined functions)
```
using `experimental_features: ['udf']` fixes is, and test could run
Fixes: #63
> datastax patch: start using `experimental_features`

- versions/scylla/3.26.3/ignore.yaml
- versions/scylla/3.26.3/patch.patch
This change introduces a patch for scylla 3.26.3 driver.
Fixes #65
ToDo:
> scylla: add patch for 3.26.3

- versions/scylla/3.25.2/patch.patch
This fixes test_1_node_cluster and test_3_node_cluster tests which would
fail due to sniproxy container getting reused during the test run.
> 3.25.x: Apply fix for sniproxy reuse issues

- versions/datastax/3.26.0/patch.patch
- versions/scylla/3.25.2/patch.patch
- versions/scylla/3.26.3/patch.patch
This change sets strict_is_not_null_in_views to False in cluster
configuration to avoid problems with `test_metadata_with_quoted_identifiers`
test.
> datastax,scylla: Add patch for strict_is_not_null_in_views config value

- versions/scylla/3.25.2/patch.patch
- versions/scylla/3.26.3/patch.patch
Adding patch for older versions based on  scylladb/python-driver#272
Task: scylladb/python-driver#228
> scylla: add patch for python-driver#272

- versions/datastax/3.29.0/patch.patch
without it some test leave thier cluster behind, failing the next round of tests
> fix(datastax): bring back missing cleanup fixture

- run.py
This commit fixes an issue where a slew of AuthenticationTests fails
due to scylla being killed during setup phase.
> run.py: lock pytest version to 7.4.4

- versions/scylla/3.26.7/ignore.yaml
- versions/scylla/3.26.7/patch.patch
Patch also applies for .8, so closing both issues with this.
Fixes #81 
Fixes #82 
[Jenkins](https://jenkins.scylladb.com/job/scylla-staging/job/alexey/job/argus-python-driver-matrix-test/34/)
> scylla: add 3.26.7 patch

- main.py
- run.py
This commit adds a new file emitted by the matrix runs, intended to
provide metadata about the run for reporting tools that are executed
later, such as Argus. Currently, the metadata file always contains the
driver name (derived from result xml name), type (in this case it's
always python), and either failure_reason key (which contains exception
stack trace that happened during .run() or path to the resulting junit
xml file relative to the metadata file.
This commit is part of ongoing task to improve matrix pipeline reporting
to Argus.
Task: scylladb/argus#289
> run.py: Introduce metadata files for runs

- scripts/run_test.sh
since cqlsh move to use shiv, it's using
this folder `~/.shiv` as a place to extract
in this docker envirment, it didn't exist, and
the user didn't had premission to create it.
mounting it as tmpfs fixes the issue.
> scripts/run_test.sh: create `~/.shiv` as tmpfs

- versions/datastax/3.29.0/ignore.yaml
Scylla discuntinued this feature.
> Disable tests with `WITH COMPACT STORAGE`

- versions/scylla/3.29.4/ignore.yaml
All patches are invalid due to:
1. Test been deleted
2. Patch was merged to the driver
So, we don't need driver anymore
> Introduce 3.29.4 patch
